### ISSUE TITLE
Can't get to run torchnlp.ner properly

### ISSUE THREAD

**Issue by aleksas** [kolloldas/torchnlp#8]
This is the result I get when following installation and running instructions:
```python
>>> train('ner-conll2003', TransformerTagger, conll2003)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "torchnlp/tasks/sequence_tagging/main.py", line 46, in train
    dataset = dataset_fn()
  File "torchnlp/data/conll.py", line 67, in conll2003_dataset
    fields=tuple(fields))
  File "/usr/local/lib/python2.7/dist-packages/torchtext/data/dataset.py", line 78, in splits
    os.path.join(path, train), **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/torchtext/datasets/sequence_tagging.py", line 33, in __init__
    examples.append(data.Example.fromlist(columns, fields))
  File "/usr/local/lib/python2.7/dist-packages/torchtext/data/example.py", line 50, in fromlist
    setattr(ex, n, f.preprocess(val))
  File "/usr/local/lib/python2.7/dist-packages/torchtext/data/field.py", line 181, in preprocess
    x = Pipeline(six.text_type.lower)(x)
  File "/usr/local/lib/python2.7/dist-packages/torchtext/data/pipeline.py", line 37, in __call__
    x = pipe.call(x, *args)
  File "/usr/local/lib/python2.7/dist-packages/torchtext/data/pipeline.py", line 52, in call
    return [self.convert_token(tok, *args) for tok in x]
TypeError: descriptor 'lower' requires a 'unicode' object but received a 'str'
```
Took conll2003 dataset files from [THIS REPO](https://github.com/synalp/NER/tree/master/corpus/CoNLL-2003)
-------------
**ENV**:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
--------------------------------
torch.__version__: 0.4.1
torchtext.__version__: 0.3.1
--------------------------------
python: 2.7.12
```

**Comment by Alexmac22347** [comment]
Hey you should try running with PyTorch version 3.5 or greater, that might fix it

**Comment by aleksas** [comment]
@Alexmac22347 correct me if I'm wrong but latest resleased pytorch version is 0.4.1 and 1.0 release candidate.
Maybe you've meant python 3.5? From the [table here](https://github.com/pytorch/pytorch) it seams that 3.5 version is the highest supported, And may have had a higher version when I tried python 3 .

**Comment by Alexmac22347** [comment]
@aleksas Sorry I meant Python 3.5! You are right. I'm running python 3.6.7 and it works for me

**Comment by aleksas** [comment]
Even worse :/
With py3 getting always 

**ENV**
```
Linux version 4.15.0-39-generic
buildd@lcy01-amd64-012
gcc version 5.4.0 20160609 
Ubuntu 5.4.0-6ubuntu1~16.04.10
#42~16.04.1-Ubuntu SMP Wed Oct 24 17:09:54 UTC 2018
-----------------
Python: 3.6.7
torch.__version__: 1.0.0.dev20181130
also 
torch.__version__: 0.4.1

```
----------------

```python
root@37cafe66fa00:/workspace/torchnlp# pytest

...

/workspace/torchnlp/tests/tasks/test_sequence_tagging.py:19: in udpos_dataset
    fields=(('inputs_word', inputs), ('labels', tags), (None, None)))
/opt/conda/lib/python3.6/site-packages/torchtext/datasets/sequence_tagging.py:66: in splits
    test=test, **kwargs)
/opt/conda/lib/python3.6/site-packages/torchtext/data/dataset.py:78: in splits
    os.path.join(path, train), **kwargs)
/opt/conda/lib/python3.6/site-packages/torchtext/datasets/sequence_tagging.py:29: in __init__
    for line in input_file:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <encodings.ascii.IncrementalDecoder object at 0x7f9df029a780>
input = b'\ntake\tVERB\tVB\nover\tADP\tRP\nAfghanistan\tPROPN\tNNP\n.\tPUNCT\t.\n\nResponse\tNOUN\tNN\n:\tPUNCT\t:\nThe\tDET\t...one\tPRON\tPRP\n\'s\tPART\tPOS\neyes\tNOUN\tNNS\noff\tADP\tIN\nthe\tDET\tDT\nformer\tADJ\tJJ\nball\tNOUN\tNN\n.\tPUNCT'
final = False

    def decode(self, input, final=False):
>       return codecs.ascii_decode(input, self.errors)[0]
E       UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 6271: ordinal not in range(128)

/opt/conda/lib/python3.6/encodings/ascii.py:26: UnicodeDecodeError

...
```

**Comment by aleksas** [comment]
@Alexmac22347 could you please provide a docker on which this package definitely works?

**Comment by kolloldas** [comment]
@aleksas are you input files in UTF-8 format?

**Comment by aleksas** [comment]
I'm running pytest on cleanly cloned repo according to the installation instructions,

On py2.7 `pytest` runs without a problem. But training raises exception as shown in initial post.
On py3.6.5 `pytest` fails on `tests/tasks/test_sequence_tagging.py` tests.

Took the CoNLL-2003 data from [HERE](https://github.com/synalp/NER/tree/master/corpus/CoNLL-2003) as it's not clear how to get the dataset from [provided link](https://github.com/kolloldas/torchnl). Tried also nyt_ingredients_ner dataset for training which resulted with the same exception.

**UPDATE**
Tried to use [pytorch dockers](https://hub.docker.com/r/pytorch/pytorch/):
- latest
- nightly-runtime-cuda9.2-cudnn7

and other dockers having py2.7 or py3

**Comment by Alexmac22347** [comment]
@aleksas Ive ran into the same unicode error. 
Might be a bit of a hack, running  `export LC_CTYPE=en_US.UTF-8` fixed it for me. https://stackoverflow.com/questions/18649512/unicodedecodeerror-ascii-codec-cant-decode-byte-0xe2-in-position-13-ordinal
Let me know if that works/doesnt work

**Comment by aleksas** [comment]
@Alexmac22347 that did the trick.
@kolloldas Made [a docker with necessary locale settings](https://github.com/kolloldas/torchnlp/pull/9) based on [pytorch v0.4.1 runtime](https://hub.docker.com/r/pytorch/pytorch/tags/) docker.

**Comment by kolloldas** [comment]
Thanks @aleksas! Merged your PR. Hope this solves your problem :)

**Comment by aleksas** [comment]
It did solve the problem, thanks!
